// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbjxljukwoubuyzvmbwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtianhsanVrd291YnV5enZtYndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDU5ODgsImV4cCI6MjA2MzkyMTk4OH0.QpRGyybvC0F73OAzoE9LYSBfyKlTWjfTBnT5JW5Egf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);